[[language]]
name = "lua"
indent = {tab-width = 3, unit = "   "}
formatter = {command = "stylua", args = ["-", "--syntax", "Lua54", "--indent-type", "Spaces", "--indent-width", "3", "--quote-style", "AutoPreferSingle", "--call-parentheses", "NoSingleTable", "--collapse-simple-statement", "Always"]}
file-types = ["lua", {glob = ".busted"}, {glob = ".luacov"}, {glob = ".luacheckrc"}, {glob = "*.rockspec"}]

[[language]]
name = "markdown"
soft-wrap = {enable = true, max-wrap = 40}

[[language]]
name = "julia"
language-servers = [ "jetls" ]
formatter = { command = "jlfmt", args = ["-"] }
auto-format = true

[language-server]
jetls = { command = "jetls", args = ["serve"] }

[[language]]
name = "xml"
language-servers = ["lemminx"]
file-types = ["xml", "openxml", {glob = "*.xml.rels"}, {glob = ".rels"}]

[language-server.lemminx]
command = "lemminx"

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
formatter = { command = "black", args = ["-"] }
auto-format = true
language-servers = ["pyright"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "bibtex"
auto-format = false

[[language]]
name = "json"
auto-format = false

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--stdin-filepath", "%{buffer_name}"] }
auto-format = false

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--stdin-filepath", "%{buffer_name}"] }
auto-format = false

[[language]]
name = "html"
auto-format = false  # Auto-format causes problems in Hugo templates.
